version: '3.8'

services:

  web_service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=domestic_service
    ports:
      - "3307:3306"





